/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;
import login.login;
import master.karyawan;
import model.jbKategori;
import connection.db_conn;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import userView.home;
/**
 *
 * @author acepmunawar
 */
public class kategori extends javax.swing.JFrame {

    /**
     * Creates new form kategori
     */
    public kategori() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        fillTable();
        auto_number();
        fld_kodekategori.setEditable(false);
        btn_delete.setEnabled(false);
        btn_update.setEnabled(false);
    }
    
      
      public ArrayList<jbKategori> getAllkategori(){
    ArrayList<jbKategori> al = null;
    al = new ArrayList<jbKategori>();
    try{
    db_conn conn = new db_conn();     
           String qry = "Select * from kategori";
           Statement st = conn.getConn().createStatement();
           ResultSet rs = st.executeQuery(qry);
    jbKategori bean;
        while(rs.next()){
              bean = new jbKategori(
                                           rs.getString("id_kategori"),
                                           rs.getString("nama_kategori"),
                          Integer.parseInt(rs.getString("no_rak"))
              );                                                   
              al.add(bean); 
     }
    }catch(Exception e){
    
    System.out.print("sory your wrong");   
    }
    return al;
}

public void fillTable(){
        ArrayList<jbKategori> al = getAllkategori();
        DefaultTableModel model = (DefaultTableModel)tablekategori.getModel();
        model.setRowCount(0);
        auto_number();
        Object[] row = new Object[10];
        for(int i =0 ; i < al.size(); i++){
            row[0] = al.get(i).getidkategori();       
            row[1] = al.get(i).getnamakategori();
            row[2] = al.get(i).getRak();
            model.addRow(row);
            
        }
    }
     
    public void showItem(int index){
        fld_kodekategori.setText(getAllkategori().get(index).getidkategori());
        fld_namakategori.setText(getAllkategori().get(index).getnamakategori());
        fld_nomorak.setText(Integer.toString(getAllkategori().get(index).getRak()));
       
    }
    
    
          private void auto_number(){
        try{
            db_conn conn = new db_conn(); 
            String sql = "SELECT MAX(right(id_kategori,2)) AS no FROM kategori";
             Statement st = conn.getConn().createStatement();
           ResultSet rs = st.executeQuery(sql);
           while (rs.next()){
               if(rs.first() == false){
                   fld_kodekategori.setText("KT001");
               
               }else{
                   rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                        for(int a = 0; a < 3 - noLong; a++){
                            no = "0" + no;
                        }
                   fld_kodekategori.setText("KT"+ no);     
               }
           }
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(this,"error: \n" + e.toString(), "kelasahan", JOptionPane.WARNING_MESSAGE); 
        
        }
    
    }
  
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnKaryawan = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnKategori = new javax.swing.JButton();
        btnKategori1 = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        id_karya2 = new javax.swing.JLabel();
        id_karya1 = new javax.swing.JLabel();
        id_karya4 = new javax.swing.JLabel();
        id_kategori = new javax.swing.JLabel();
        fld_searchkategori = new javax.swing.JTextField();
        fld_nomorak = new javax.swing.JTextField();
        fld_namakategori = new javax.swing.JTextField();
        fld_kodekategori = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablekategori = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PT GARMAK MOTOR");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master/gm2.jpg"))); // NOI18N
        jLabel9.setText("jLabel3");

        btnKaryawan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnKaryawan.setText("Karyawan");
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });

        btnSupplier.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSupplier.setText("Supplier");
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnBarang.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBarang.setText("Barang");
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnKategori.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnKategori.setText("Kategori");
        btnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriActionPerformed(evt);
            }
        });

        btnKategori1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnKategori1.setText("User ");
        btnKategori1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategori1ActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLogOut.setText("logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setText("DATA KATEGORI");

        id_karya2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id_karya2.setText("KODE KATEGORI");

        id_karya1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id_karya1.setText("NAMA KATEGORI");

        id_karya4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id_karya4.setText("NOMOR RAK");

        id_kategori.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id_kategori.setText("SEARCH KATEGORI");

        fld_searchkategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fld_searchkategoriMouseClicked(evt);
            }
        });
        fld_searchkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_searchkategoriActionPerformed(evt);
            }
        });
        fld_searchkategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fld_searchkategoriKeyReleased(evt);
            }
        });

        fld_nomorak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_nomorakActionPerformed(evt);
            }
        });

        fld_namakategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_namakategoriActionPerformed(evt);
            }
        });

        fld_kodekategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_kodekategoriActionPerformed(evt);
            }
        });

        tablekategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode kategori", "Nama ", "Rak"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablekategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablekategoriMouseClicked(evt);
            }
        });
        tablekategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablekategoriKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablekategori);
        if (tablekategori.getColumnModel().getColumnCount() > 0) {
            tablekategori.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete-32.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Modify.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Refresh-32.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(id_kategori, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_karya1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_karya2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_karya4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(fld_searchkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(fld_kodekategori, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fld_nomorak, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fld_namakategori, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(723, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_kodekategori, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_karya2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_namakategori, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_karya1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_nomorak, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_karya4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_searchkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_kategori))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fld_searchkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_searchkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_searchkategoriActionPerformed

    private void fld_nomorakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_nomorakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_nomorakActionPerformed

    private void fld_namakategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_namakategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_namakategoriActionPerformed

    private void fld_kodekategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_kodekategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_kodekategoriActionPerformed

    private void tablekategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablekategoriMouseClicked
        // TODO add your handling code here:
      
        btn_save.setEnabled(false);
        btn_update.setEnabled(true);
        btn_delete.setEnabled(true);
        int ind = tablekategori.getSelectedRow();
        showItem(ind);
    }//GEN-LAST:event_tablekategoriMouseClicked

    private void tablekategoriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablekategoriKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_tablekategoriKeyReleased

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
                // TODO add your handling code here:
        int okay = JOptionPane.showConfirmDialog(null,"Apakah Yakin Menghapus data ini???", "Ijinkan",JOptionPane.YES_NO_CANCEL_OPTION);        
               if(
               fld_kodekategori.getText().toString().equals("") ||
               fld_namakategori.getText().toString().equals("") ||
               fld_nomorak.getText().toString().equals("") 
               )
       {
           JOptionPane.showMessageDialog(null, "semua kolom harus di isi .....");
       }else{
               if(okay == 0){    
           try{
                db_conn conn = new db_conn();
                String qry = "delete from kategori where id_kategori=?";
                PreparedStatement ps = conn.getConn().prepareStatement(qry);
                ps.setString(1,fld_kodekategori.getText().toString());
                int result = ps.executeUpdate();
                fillTable();
                if(result >= 1){
                            btn_clear.setEnabled(true);
        btn_save.setEnabled(true);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
                    JOptionPane.showMessageDialog(null,result + "data berhasil di hapus "+ fld_kodekategori.getText().toString());
                }else{
                    JOptionPane.showMessageDialog(null,"data gagal di hapus .......");        
                        if (ps!=null){
                        ps.close();        
                }
                    if (conn != null){
                    conn.getConn().close();
                }
                }            
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, "masalah pada dbms : "+ e);                         
           }
               }
               //clear the filds
              
               fld_namakategori.setText("");    
               fld_nomorak.setText("");
              
       }                            
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        if(
            fld_kodekategori.getText().toString().equals("") ||    
            fld_namakategori.getText().toString().equals("") ||
            fld_nomorak.getText().toString().equals("")
            
        )
        {
            JOptionPane.showMessageDialog(null, "semua kolom harus di isi .....");
        }else{
            try{
                db_conn conn = new db_conn();
                String qry = "update kategori set nama_kategori=?, no_rak=? where id_kategori=?";
                PreparedStatement ps = conn.getConn().prepareStatement(qry);

                ps.setString(1,fld_namakategori.getText().toString());
                ps.setInt(2,Integer.parseInt(fld_nomorak.getText().toString()));
                ps.setString(3,fld_kodekategori.getText().toString());
                int result = ps.executeUpdate();
                fillTable();
                if(result >= 1){
                            btn_clear.setEnabled(true);
        btn_save.setEnabled(true);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
                    JOptionPane.showMessageDialog(null,result + "update sukses.... "+ fld_kodekategori.getText().toString());
                }else{
                    JOptionPane.showMessageDialog(null,"update gagal .......");
                    if (ps!=null){
                        ps.close();
                    }
                }if (conn != null){
                    conn.getConn().close();
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "masalah pada dbms : "+ e);
            }
            //clear the filds
    
            fld_namakategori.setText("");
            fld_nomorak.setText("");

        }

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        // tombol simpan
        if(
    
            fld_namakategori.getText().toString().equals("") ||
            fld_nomorak.getText().toString().equals("") 
        )
        {
            JOptionPane.showMessageDialog(null, "all fields are compulsory .....");
        }else{
            try{

                db_conn conn = new db_conn();
                String qry = "insert into kategori(id_kategori,nama_kategori,no_rak) values(?,?,?)";
                PreparedStatement ps = conn.getConn().prepareStatement(qry);
                ps.setString(1,fld_kodekategori.getText().toString());
                ps.setString(2,fld_namakategori.getText().toString());
                ps.setString(3,fld_nomorak.getText().toString());
                int result = ps.executeUpdate();
                fillTable();
                if(result >= 1){
                    JOptionPane.showMessageDialog(null,result + "data berhasil disimpan .... ");
                }else{
                    JOptionPane.showMessageDialog(null, result + "gagal menyimpan .......");
                    if (ps!=null){
                        ps.close();

                    }
                }if (conn != null){
                    conn.getConn().close();

                }

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "masalah pada dbms : "+ e);

            }
            //clear the filds
            fld_namakategori.setText("");
            fld_nomorak.setText("");

        }

    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
kategori kt = new kategori();
kt.setVisible(true);
this.setVisible(false);
     

    }//GEN-LAST:event_btn_clearActionPerformed

    private void fld_searchkategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fld_searchkategoriMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_fld_searchkategoriMouseClicked

    private void fld_searchkategoriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fld_searchkategoriKeyReleased
        // TODO add your handling code here:
         ArrayList<jbKategori> al = null;
        al = new ArrayList<jbKategori>();
        String val = fld_searchkategori.getText().toString();
        
        try{
            db_conn conn = new db_conn();
            String qry = "SELECT * FROM kategori WHERE id_kategori like '%" + val +"%'"+"or nama_kategori like '%"+ val +"%'"+"or no_rak like '%"+ val +"%'" ;
            Statement st = conn.getConn().createStatement();
            ResultSet rs = st.executeQuery(qry);
            jbKategori teacher;
             jbKategori bean;
        while(rs.next()){
              bean = new jbKategori(
                          rs.getString(1),
                          rs.getString(2),
                          Integer.parseInt(rs.getString(3)));                                                   
              al.add(bean);
     }
              
                   DefaultTableModel model = (DefaultTableModel)tablekategori.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        for(int i =0 ; i < al.size(); i++){
            row[0] = al.get(i).getidkategori();       
            row[1] = al.get(i).getnamakategori();
            row[2] = al.get(i).getRak();
            model.addRow(row);             
        }
        
        if (st!=null){
                st.close();
        
        }
        if (conn != null){
                conn.getConn().close();
        }           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error at JtextField1_searchKeyReleased " + e);
        
        
        }
    }//GEN-LAST:event_fld_searchkategoriKeyReleased

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        karyawan kr = new karyawan();
        kr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        supplier supplier = new supplier();
        supplier.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        barang barang = new barang();
        barang.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriActionPerformed
        kategori kategori = new kategori();
        kategori.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKategoriActionPerformed

    private void btnKategori1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategori1ActionPerformed
        // TODO add your handling code here:
        userLogin ug = new userLogin();
        ug.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKategori1ActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        login logout = new login();
        logout.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // btnBmasuk
        home bm = new home();
        bm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnKategori;
    private javax.swing.JButton btnKategori1;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField fld_kodekategori;
    private javax.swing.JTextField fld_namakategori;
    private javax.swing.JTextField fld_nomorak;
    private javax.swing.JTextField fld_searchkategori;
    private javax.swing.JLabel id_karya1;
    private javax.swing.JLabel id_karya2;
    private javax.swing.JLabel id_karya4;
    private javax.swing.JLabel id_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablekategori;
    // End of variables declaration//GEN-END:variables
}
