/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;

import connection.db_conn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import login.login;
import master.karyawan;
import model.jBsupplier;
import userView.home;
/**
 *
 * @author acepmunawar
 */
public class supplier extends javax.swing.JFrame {
    /**
     * Creates new form supplier
     */
    public supplier() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        fillTable();
        auto_number();
        fld_idsupplier.setEditable(false);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
    }

    
    public ArrayList<jBsupplier> getAllSupData(){
    ArrayList<jBsupplier> al = null;
    al = new ArrayList<jBsupplier>();
    try{
    db_conn db = new db_conn();     
           String qry = "Select * from supplier ";
           Statement st = db.getConn().createStatement();
           ResultSet rs = st.executeQuery(qry);
    jBsupplier beanS;
        while(rs.next()){
              beanS = new jBsupplier(
                          rs.getString(1),
                          rs.getString(2),
                          rs.getString(3),
                          rs.getString(4));                                                   
              al.add(beanS);

     }
    }catch(Exception e){
    
    System.out.print("sory your wrong");   
    }
    return al;
}
    
public void fillTable(){
        ArrayList<jBsupplier> al = getAllSupData();
        DefaultTableModel model = (DefaultTableModel)tablesupplier.getModel();
        model.setRowCount(0);
        auto_number();
        Object[] row = new Object[5];
        for(int i =0 ; i < al.size(); i++){
            row[0] = al.get(i).getIdSupplier();       
            row[1] = al.get(i).getNamaSupplier();
            row[2] = al.get(i).getAlamatSupplier();
            row[3] = al.get(i).getNoSupplier();
            model.addRow(row);        
        }
    }
        
    public void showItem(int index){      
        fld_idsupplier.setText(getAllSupData().get(index).getIdSupplier()); 
        fld_namaSupplier.setText(getAllSupData().get(index).getNamaSupplier());
        fld_alamatSupplier.setText(getAllSupData().get(index).getAlamatSupplier());
        fld_nomorSupplier.setText(getAllSupData().get(index).getNoSupplier());
    }
           
    
    
          private void auto_number(){
        try{
            db_conn conn = new db_conn(); 
            String sql = "SELECT MAX(right(id_supplier,2)) AS no FROM supplier";
             Statement st = conn.getConn().createStatement();
           ResultSet rs = st.executeQuery(sql);
           while (rs.next()){
               if(rs.first() == false){
                   fld_idsupplier.setText("SU001");
               
               }else{
                   rs.last();
                   int auto_id = rs.getInt(1) + 1;
                   String no = String.valueOf(auto_id);
                   int noLong = no.length();
                        for(int a = 0; a < 3 - noLong; a++){
                            no = "0" + no;
                        }
                   fld_idsupplier.setText("SU"+ no);     
               }
           }
        }catch(Exception e){
        
            JOptionPane.showMessageDialog(this,"error: \n" + e.toString(), "kelasahan", JOptionPane.WARNING_MESSAGE); 
        
        }
    
    }
  
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnKaryawan = new javax.swing.JButton();
        btnSupplier = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnKategori = new javax.swing.JButton();
        btnKategori1 = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        fld_idsupplier = new javax.swing.JTextField();
        fld_namaSupplier = new javax.swing.JTextField();
        fld_nomorSupplier = new javax.swing.JTextField();
        fld_alamatSupplier = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        id_karya1 = new javax.swing.JLabel();
        id_karya2 = new javax.swing.JLabel();
        id_karya3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablesupplier = new javax.swing.JTable();
        btn_clear = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        fld_nomorSupplier1 = new javax.swing.JTextField();
        id_karya4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setText("SUPPLIER");

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PT GARMAK MOTOR");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master/gm2.jpg"))); // NOI18N
        jLabel9.setText("jLabel3");

        btnKaryawan.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnKaryawan.setText("Karyawan");
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });

        btnSupplier.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSupplier.setText("Supplier");
        btnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierActionPerformed(evt);
            }
        });

        btnBarang.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBarang.setText("Barang");
        btnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangActionPerformed(evt);
            }
        });

        btnKategori.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnKategori.setText("Kategori");
        btnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriActionPerformed(evt);
            }
        });

        btnKategori1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnKategori1.setText("User ");
        btnKategori1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategori1ActionPerformed(evt);
            }
        });

        btnLogOut.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLogOut.setText("logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(71, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );

        fld_idsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fld_idsupplierActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("ID");

        id_karya1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id_karya1.setText("NAMA");

        id_karya2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id_karya2.setText("ALAMAT");

        id_karya3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id_karya3.setText("NO TLP");

        tablesupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Nomor"
            }
        ));
        tablesupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablesupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablesupplier);
        if (tablesupplier.getColumnModel().getColumnCount() > 0) {
            tablesupplier.getColumnModel().getColumn(3).setResizable(false);
        }

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Refresh-32.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Modify.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete-32.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        fld_nomorSupplier1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fld_nomorSupplier1KeyReleased(evt);
            }
        });

        id_karya4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id_karya4.setText("SEARCH SUPPLIER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 562, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(id_karya4)
                                .addGap(115, 115, 115)
                                .addComponent(fld_nomorSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(id_karya2)
                                        .addComponent(id_karya1)
                                        .addComponent(jLabel4)
                                        .addComponent(id_karya3))
                                    .addGap(113, 113, 113)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fld_nomorSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fld_alamatSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                                            .addComponent(fld_namaSupplier, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fld_idsupplier, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(413, 413, 413))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fld_idsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_karya1)
                    .addComponent(fld_namaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_karya2)
                    .addComponent(fld_alamatSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_karya3)
                    .addComponent(fld_nomorSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_karya4)
                    .addComponent(fld_nomorSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fld_idsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fld_idsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fld_idsupplierActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // tombol simpan
            if(
               fld_namaSupplier.getText().toString().equals("") ||
               fld_alamatSupplier.getText().toString().equals("") ||
               fld_nomorSupplier.getText().toString().equals("") 
               )
       {
           JOptionPane.showMessageDialog(null, "all fields are compulsory .....");
       }else{
           try{
               
                db_conn conn = new db_conn();
                String qry = "insert into supplier(id_supplier,namaSupplier,alamatSupplier,noSupplier) values(?,?,?,?)";
                PreparedStatement ps = conn.getConn().prepareStatement(qry);
                ps.setString(1,fld_idsupplier.getText().toString());
                ps.setString(2,fld_namaSupplier.getText().toString()); 
                ps.setString(3,fld_alamatSupplier.getText().toString());
                ps.setString(4,fld_nomorSupplier.getText().toString());
               int result = ps.executeUpdate();
               fillTable();
                if(result >= 1){
                    JOptionPane.showMessageDialog(null,result + "data berhasil disimpan .... ");
                }else{
                    JOptionPane.showMessageDialog(null, result + "gagal menyimpan .......");
                if (ps!=null){
                    ps.close();
        
                }                    
                }if (conn != null){
                    conn.getConn().close();
                
                }   
                        
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, "masalah pada dbms : "+ e);
                         
           }
               //clear the filds
               
               fld_namaSupplier.setText("");
               fld_alamatSupplier.setText("");
               fld_nomorSupplier.setText("");

        }       
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
           if(         
               fld_namaSupplier.getText().toString().equals("") ||
               fld_alamatSupplier.getText().toString().equals("") ||
               fld_nomorSupplier.getText().toString().equals("") 
               )
       {
           JOptionPane.showMessageDialog(null, "semua kolom harus terisi .....");
       }else{
           try{
               db_conn conn = new db_conn();
                String qry = "update supplier set namaSupplier=?, alamatSupplier=?, noSupplier=? where id_supplier=?";
                PreparedStatement ps = conn.getConn().prepareStatement(qry);
         
                ps.setString(1,fld_namaSupplier.getText().toString());
                ps.setString(2,fld_alamatSupplier.getText().toString());
                ps.setString(3,fld_nomorSupplier.getText().toString());
                ps.setString(4,fld_idsupplier.getText().toString());
                int result = ps.executeUpdate();
                    fillTable();
                if(result >= 1){
                            btn_clear.setEnabled(true);
        btn_save.setEnabled(true);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
                      JOptionPane.showMessageDialog(null,result + "update sukses .... "+ fld_idsupplier.getText().toString());
        
                }else{
                    JOptionPane.showMessageDialog(null,"update gagal .......");
        
                 if (ps!=null){
                    ps.close();
        
                }                    
                }if (conn != null){
                    conn.getConn().close();
                
                }        
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, "masalah pada dbms : "+ e);
                         
           }
               //clear the filds
               fld_namaSupplier.setText("");
               fld_alamatSupplier.setText("");
               fld_nomorSupplier.setText("");   
       }       
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
         int okay = JOptionPane.showConfirmDialog(null,"Apakah Yakin Menghapus data ini???", "Ijinkan",JOptionPane.YES_NO_CANCEL_OPTION);
        
               if(
               fld_namaSupplier.getText().toString().equals("") ||
               fld_alamatSupplier.getText().toString().equals("") ||
               fld_nomorSupplier.getText().toString().equals("") 
               )
       {
           JOptionPane.showMessageDialog(null, "semua kolom harus di isi .....");
       }else{
               if(okay == 0){    
           try{
                db_conn conn = new db_conn();
                String qry = "delete from supplier where id_supplier=?";
                PreparedStatement ps = conn.getConn().prepareStatement(qry);
                ps.setString(1,fld_idsupplier.getText().toString());
                int result = ps.executeUpdate();
                fillTable();
                if(result >= 1){
                     btn_clear.setEnabled(true);
        btn_save.setEnabled(true);
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
                    JOptionPane.showMessageDialog(null,result + "data berhasil di hapus "+ fld_idsupplier.getText().toString());
                }else{
                    JOptionPane.showMessageDialog(null,"gagal hapus coba lagi .......");
        
                        if (ps!=null){
                        ps.close();
        
                }
                    if (conn != null){
                    conn.getConn().close();
                }
                }             
           }catch(Exception e){
               JOptionPane.showMessageDialog(null, "masalah pada dbms : "+ e);
                          
           }
               }
               //clear the filds
     fld_namaSupplier.setText("");
               fld_alamatSupplier.setText("");
               fld_nomorSupplier.setText("");
 
       }     
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tablesupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablesupplierMouseClicked
        // TODO add your handling code here:


        btn_save.setEnabled(false);
        btn_update.setEnabled(true);
        btn_delete.setEnabled(true);
        int ind = tablesupplier.getSelectedRow();
        showItem(ind);
    }//GEN-LAST:event_tablesupplierMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
supplier sup = new supplier();
sup.setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void fld_nomorSupplier1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fld_nomorSupplier1KeyReleased
        // TODO add your handling code here:
           // TODO add your handling code here:
        ArrayList<jBsupplier> al = null;
        al = new ArrayList<jBsupplier>();
        String val = fld_nomorSupplier1.getText().toString();
        
        try{
            db_conn conn = new db_conn();
            String qry = "SELECT * FROM supplier WHERE id_supplier like '%" + val +"%'"+"or namaSupplier like '%"+ val +"%'"+"or alamatSupplier like '%"+ val +"%'"+"or noSupplier like '%"+ val +"%'" ;
            Statement st = conn.getConn().createStatement();
            ResultSet rs = st.executeQuery(qry);
            jBsupplier teacher;
      jBsupplier beanS;
        while(rs.next()){
              beanS = new jBsupplier(
                          rs.getString(1),
                          rs.getString(2),
                          rs.getString(3),
                          rs.getString(4));                                                   
              al.add(beanS);

     }
              
                   DefaultTableModel model = (DefaultTableModel)tablesupplier.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        for(int i =0 ; i < al.size(); i++){
            row[0] = al.get(i).getIdSupplier();       
            row[1] = al.get(i).getNamaSupplier();
            row[2] = al.get(i).getAlamatSupplier();
            row[3] = al.get(i).getNoSupplier();
            model.addRow(row);             
        }
        
        if (st!=null){
                st.close();
        
        }
        if (conn != null){
                conn.getConn().close();
        }           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error at JtextField1_searchKeyReleased " + e);
        
        
        }
    }//GEN-LAST:event_fld_nomorSupplier1KeyReleased

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        karyawan kr = new karyawan();
        kr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierActionPerformed
        supplier supplier = new supplier();
        supplier.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSupplierActionPerformed

    private void btnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangActionPerformed
        barang barang = new barang();
        barang.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBarangActionPerformed

    private void btnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriActionPerformed
        kategori kategori = new kategori();
        kategori.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKategoriActionPerformed

    private void btnKategori1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategori1ActionPerformed
        // TODO add your handling code here:
        userLogin ug = new userLogin();
        ug.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnKategori1ActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        login logout = new login();
        logout.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // btnBmasuk
        home bm = new home();
        bm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnKategori;
    private javax.swing.JButton btnKategori1;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSupplier;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JTextField fld_alamatSupplier;
    private javax.swing.JTextField fld_idsupplier;
    private javax.swing.JTextField fld_namaSupplier;
    private javax.swing.JTextField fld_nomorSupplier;
    private javax.swing.JTextField fld_nomorSupplier1;
    private javax.swing.JLabel id_karya1;
    private javax.swing.JLabel id_karya2;
    private javax.swing.JLabel id_karya3;
    private javax.swing.JLabel id_karya4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablesupplier;
    // End of variables declaration//GEN-END:variables
}
